spring:
  application:
    name: eolmago
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
      validation-timeout: 2000
      idle-timeout: 300000
      max-lifetime: 1740000
      keepalive-time: 120000

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
